/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package postgui.payment;

import Transactions.payment.Check;
import Transactions.payment.Payment;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Tony
 */
public class GPaymentCheckPanel extends javax.swing.JPanel {

    /**
     * Creates new form GPaymentCheckPanel
     */
    public GPaymentCheckPanel(JPanel parent) {
        initComponents();
        this.parent = (GPaymentPanel) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCheck = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnPayCheck = new javax.swing.JButton();

        lblCheck.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCheck.setText("Amount");
        lblCheck.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtAmount.setToolTipText("");
        txtAmount.setMaximumSize(new java.awt.Dimension(58, 19));
        txtAmount.setMinimumSize(new java.awt.Dimension(58, 19));
        txtAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAmountKeyReleased(evt);
            }
        });

        btnPayCheck.setText("Pay");
        btnPayCheck.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayCheckMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPayCheck, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPayCheck, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPayCheckMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayCheckMouseClicked
        if (this.txtAmount.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Invalid Check Amount.", "Check Error", JOptionPane.ERROR_MESSAGE);
            return;
        } else if (Integer.parseInt(this.txtAmount.getText()) < 0) {
            JOptionPane.showMessageDialog(this, "Mus give Positive Check Amount.", "Check Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        try {
            double amnt_given = Double.parseDouble(this.txtAmount.getText());
            Payment cp = new Check(amnt_given);
            this.parent.sendPaymentToFrame(cp);
        } catch (NumberFormatException ex) {

        } catch (RemoteException ex) {
            Logger.getLogger(GPaymentCheckPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPayCheckMouseClicked

    private void txtAmountKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAmountKeyReleased
        String tmp = this.txtAmount.getText();
        if (tmp.length() < 1) {
            return;
        }
        if (!tmp.matches(this.regex)) {
            this.txtAmount.setText(tmp.substring(0, tmp.length() - 1));
        }

    }//GEN-LAST:event_txtAmountKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPayCheck;
    private javax.swing.JLabel lblCheck;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration//GEN-END:variables
    private final String regex = "\\d+";
    private final GPaymentPanel parent;
}
